name: Sync Gist to ED File
on:
  schedule:
    - cron: '0 11 * * *'  # 每天UTC时间2点执行
  workflow_dispatch:  # 支持手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Gist Content
        run: |
          wget -O ED-file.ed https://gist.githubusercontent.com/WLget/aeb222e378a8dcbd74e06413dbacf400/raw/base64.ed
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ED-file.ed
          git commit -m "自动更新ED文件"
          git push
