name: Sync MD to README
permissions: write-all
on:
  schedule:
    - cron: "*/33 * * * *"  # 每33分钟同步一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 下载外部MD文件
        run: |
          wget -O external.md https://raw.githubusercontent.com/WLget/V2Ray_configs_64/refs/heads/master/ConfigSub_list.md

      - name: 合并到README
        run: |
          # 插入到README的指定位置（示例：在特定注释后追加）
          sed -i '/<!-- INSERT_POINT -->/r ConfigSub_list.md' README.md
      - name: 提交变更
        uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "合并文件更新"
          committer: "GitHub Actions <actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
