name: Sync MD to README
on:
  schedule:
    - cron: "50 * * * *"  # 每小时的第0分钟执行（UTC时间）
  workflow_dispatch:     # 支持手动触发

permissions:  # 关键权限配置[7](@ref)
  contents: write       # 允许写入README.md

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 下载外部文件
        run: |
          # 二进制模式下载（网页6）
          curl -L --retry 3 --max-time 30 -o ConfigSub_list.txt \
            https://raw.githubusercontent.com/WLget/V2Ray_configs_64/master/ConfigSub_list.txt

          # 强制转换编码（网页1）
          encoding=$(file -b --mime-encoding ConfigSub_list.txt | cut -d'/' -f2)
          iconv -f $encoding -t UTF-8 ConfigSub_list.txt -o temp.txt
          mv temp.txt ConfigSub_list.txt

          # 统一换行符（网页6）
          sed -i 's/\r$//' ConfigSub_list.txt

      - name: 合并到README
        run: |
          # 创建临时工作区（网页4）
          cp README.md README.bak

          # 精确插入内容（网页3）
          awk '/<!-- TEXTBOX_START -->/{print;system("cat ConfigSub_list.txt");next}1' README.bak > README.md

          # 清理备份（网页4）
          rm README.bak

      - name: 提交变更
        uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "AutoSync"
